repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: local
    hooks:
      - id: validate-notebooks
        name: validate notebooks
        entry: python scripts/validate_notebooks.py
        language: system
        pass_filenames: false
